"""add is_deleted to categories

Revision ID: c6564062e27b
Revises: 90020d2b9601
Create Date: 2026-06-02 23:11:39.511792

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c6564062e27b"
down_revision: str | Sequence[str] | None = "90020d2b9601"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("categories", sa.Column("is_deleted", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("categories", "is_deleted")
    # ### end Alembic commands ###
